"use client";

import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { ScriptVariant } from "@/lib/scripts/types";
import { estimateRuntimeSeconds } from "@/lib/scripts/format";

const colors = {
  cream: "#fdf8ed",
  ink: "#1f2a30",
  muted: "#6c7780",
  orange: "#cd6028",
  navy: "#325269",
  line: "#d9cdb6",
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.cream,
    paddingTop: 36,
    paddingBottom: 36,
    paddingHorizontal: 40,
    fontFamily: "Helvetica",
    color: colors.ink,
    fontSize: 10.5,
    lineHeight: 1.5,
  },
  pill: {
    alignSelf: "flex-start",
    backgroundColor: colors.orange,
    color: "white",
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1.2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 8,
    borderRadius: 3,
  },
  eyebrow: {
    fontSize: 8,
    color: colors.orange,
    letterSpacing: 1.5,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  title: {
    fontSize: 26,
    color: colors.navy,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1,
    marginBottom: 4,
  },
  angle: {
    fontStyle: "italic",
    fontSize: 11,
    color: colors.muted,
    marginBottom: 12,
  },
  meta: {
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8.5,
    color: colors.muted,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.8,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: colors.line,
    marginBottom: 18,
  },
  scriptBlock: {
    fontFamily: "Courier",
    fontSize: 10,
    lineHeight: 1.55,
    color: colors.ink,
    backgroundColor: "white",
    padding: 14,
    borderWidth: 0.75,
    borderColor: colors.line,
    borderRadius: 4,
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 40,
    right: 40,
    fontSize: 8,
    color: colors.muted,
    letterSpacing: 1,
  },
});

type DocProps = {
  variants: ScriptVariant[];
  meta: { date: string; runtime?: number; variantNumber?: number };
};

// Plain builder, not a React component — @react-pdf/renderer's `pdf()` wants a
// ReactElement<DocumentProps>, not a FunctionComponentElement that wraps one.
export function buildScriptPdf({ variants, meta }: DocProps) {
  return (
    <Document>
      {variants.map((v, i) => {
        const runtime =
          v.runtime_estimate_seconds || estimateRuntimeSeconds(v.script);
        return (
          <Page key={i} size="LETTER" style={styles.page}>
            <Text style={styles.pill}>DITCH HOSPITALITY GROUP</Text>
            <Text style={styles.eyebrow}>SHOOTING SCRIPT</Text>
            <Text style={styles.title}>{v.name}</Text>
            <Text style={styles.angle}>{v.angle}</Text>
            <View style={styles.meta}>
              <Text>~{runtime}s estimated runtime</Text>
              <Text>
                {meta.variantNumber ? `Variant ${meta.variantNumber} · ` : ""}
                {meta.date}
              </Text>
            </View>
            <View style={styles.scriptBlock}>
              <Text>{v.script}</Text>
            </View>
            <Text style={styles.footer}>
              Internal — generated by Ditch Scripts
            </Text>
          </Page>
        );
      })}
    </Document>
  );
}
